title: Christine's Blog
author: GitHub User - Christine Becker
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my site! I can't wait to see what this brings us :)


show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
